nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ["Content-Type", "Authorization", "Accept", "Cookie"]
        expose_headers:
            - "Link"
            - "x-pagination-total-count"
            - "x-pagination-page-count"
            - "x-pagination-current-page"
            - "x-pagination-per-page"
        max_age: 3600
    paths:
        '^/': null
